baseURL = "http://gocv.io/"
languageCode = "en-us"
title = "GoCV - Golang Computer Vision Using OpenCV 3"
theme = "learn"

[params]
  # Disable search function. It will hide search bar
  disableSearch = true

[[menu.shortcuts]] 
name = "<i class='fa fa-github'></i> Github repo"
url = "https://github.com/hybridgroup/gocv"
weight = 10

[[menu.shortcuts]] 
name = "<i class='fa fa-book'></i> Godoc"
url = "https://godoc.org/github.com/hybridgroup/gocv"
weight = 20
